on: [push, pull_request]
name: PHPCs
jobs:
  php-cs-fixer:
    name: PHP-CS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: PHP-CS-Fixer
      uses: docker://oskarstark/phpcs-ga
